config/routes.rb
IndivProj::Application.routes.draw do
  get "welcome/index"
  get 'invoices/generate(.:format)' => 'invoices#generate', as: 'generate'
  resources :invoices

  resources :timeslots

  resources :appointments

  resources :diagnostic_codes

  resources :physicians

  resources :patients

  root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :timeslot
  belongs_to :invoice
  has_and_belongs_to_many :diagnostic_codes
  belongs_to :diagnostic_code

  def appointment_avail
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @invoice = Invoice.new
    @appointments = Appointment.all
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :timeslot_id, :physician_id, :note, :diagnostic_code_id, :patient_id, :reason)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table style="width:50%" align="center">
  <tr>
  <td>
    <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </td>
 <td>
    <div class="field">
    <%= f.label :timeslot_id %><br>
    <%= f.number_field :timeslot_id %>
 </td>
    </tr>

  <tr>
  <td>
    <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id,Physician.all,:id,:name %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :patient_id %> <%= link_to 'New Patient?', new_patient_path %>  <br>
    <%= f.collection_select :patient_id,Patient.all,:id,:name %>
  </div>
    </td>
  </tr>
  </table>
  <table style="width:50%" align="center">
  <tr>
  <td>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  </td>
  </tr>
  </table>


    <div class="action" align="center">
    <%= f.submit %>
  </div>


<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Timeslot</th>
      <th>Physician</th>
      <th>Note</th>
      <th>Diagnostic code</th>
      <th>Patient</th>
      <th>Reason</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

    <div> <% @ct = (Time.now - 6.hours) %>
    </div><br>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>

        <td><%=appointment.timeslot.time %>
        <% @t = Time.parse(appointment.timeslot.time) %>
        <% @d = "#{appointment.date} #{appointment.timeslot.time}" %>
        <% @d = Time.parse(@d) %>
        </td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.note %></td>
        <td><%= appointment.diagnostic_code.number %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.reason %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <% if (((@d - @ct) / 1.hour).round) > 8 %>
           <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<center><h2>New appointment</h2>

<%= render 'form' %>

  <%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Timeslot:</strong>
  <%= @appointment.timeslot.time %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @appointment.note %>
</p>

<p>
  <strong>Diagnostic code:</strong>
  <%= @appointment.diagnostic_code.number %>
</p>

<p>
  <strong>Diagnostic code:</strong>
  <%= @appointment.diagnostic_code.description %>
</p>

<p>
  <strong>Diagnostic cost:</strong>
  <%@cost = @appointment.diagnostic_code.cost %>
  <%= number_to_currency(@cost) %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>
<%= link_to 'Edit', edit_appointment_path(@appointment) %>
<br><br>

<p>
  <strong>Generate Invoice:</strong>
</p>

<%= form_for(@invoice) do |f| %>
    <% if @invoice.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

          <ul>
            <% @invoice.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :amount %><br>
      <%= f.text_field :amount, :value => @cost, :readonly=>true %>
    </div>
    <div class="field">
      <%= f.label :patient_id %><br>
      <%= f.number_field :patient_id, :value => @appointment.patient_id, :readonly=>true%>
    </div>
    <div class="field">
      <%= f.label :appointment_id %><br>
      <%= f.number_field :appointment_id, :value => @appointment.patient_id, :readonly=>true %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Back', appointments_path %>