config/routes.rb
IndivProj::Application.routes.draw do
  get "welcome/index"
  get 'invoices/generate(.:format)' => 'invoices#generate', as: 'generate'
  resources :invoices

  resources :timeslots

  resources :appointments

  resources :diagnostic_codes

  resources :physicians

  resources :patients

  root 'welcome#index'

end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  has_many :appointments
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :set_timeslot, only: [:show, :edit, :update, :destroy]

  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
  end

  # GET /timeslots/new
  def new
    @timeslot = Timeslot.new
  end

  # GET /timeslots/1/edit
  def edit
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(timeslot_params)

    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timeslot }
      else
        format.html { render action: 'new' }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timeslots/1
  # PATCH/PUT /timeslots/1.json
  def update
    respond_to do |format|
      if @timeslot.update(timeslot_params)
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot.destroy
    respond_to do |format|
      format.html { redirect_to timeslots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeslot
      @timeslot = Timeslot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeslot_params
      params.require(:timeslot).permit(:time)
    end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/timeslots/_form.html.erb
<%= form_for(@timeslot) do |f| %>
  <% if @timeslot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
      <% @timeslot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing timeslot</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<h1>Listing timeslots</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td><%= timeslot.time %></td>
        <td><%= link_to 'Show', timeslot %></td>
        <td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
        <td><%= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeslot', new_timeslot_path %>

app/views/timeslots/new.html.erb
<h1>New timeslot</h1>

<%= render 'form' %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @timeslot.time %>
</p>

<%= link_to 'Edit', edit_timeslot_path(@timeslot) %> |
<%= link_to 'Back', timeslots_path %>