config/routes.rb
IndivProj::Application.routes.draw do
  get "welcome/index"
  get 'invoices/generate(.:format)' => 'invoices#generate', as: 'generate'
  resources :invoices

  resources :timeslots

  resources :appointments

  resources :diagnostic_codes

  resources :physicians

  resources :patients

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Dermascheduler Pro</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <% @t = Time.now.in_time_zone("Central Time (US & Canada)") %>
  <% @t = @t.strftime("%I:%M %p") %>


  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Home', welcome_index_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li></li>
        <li class="has-dropdown">
          <a href="#">Menu</a>
          <ul class="dropdown">
            <li><%= link_to 'New Patient', new_patient_path %></li>
            <li><%= link_to 'List Patients', patients_path %></li>
            <li><%= link_to 'New Appointment', new_appointment_path %></li>
            <li><%= link_to 'List Appointments', appointments_path %></li>
            <li><%= link_to 'New Physician', new_physician_path %></li>
            <li><%= link_to 'List Physicians', physicians_path %></li>
            <li><%= link_to 'List Invoices', invoices_path %></li>
            <li><%= link_to 'List Diagnostic Codes', diagnostic_codes_path %></li>
            <li><%= link_to 'New Diagnostic Code', new_diagnostic_code_path %></li>

          </ul>
        </li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
      </ul>
    </section>
  </nav>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>